# DataFrame的基本用法

In [1]:
import pandas as pd
import numpy as np

In [5]:
#实际上，针对二维的numpy数组，行列同dataframe的行列是一致的。
arr1 = np.arange(12).reshape(3,4)
print(arr1)
df1 = pd.DataFrame(arr1,index=['A','B','C'],columns=['a','b','c','d'])
df1

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


a  b   c   d
A  0  1   2   3
B  4  5   6   7
C  8  9  10  11

### 1.T转置

In [12]:
#转置不改变原有的数据
df2 = df1.T
df2

A  B   C
a  0  4   8
b  1  5   9
c  2  6  10
d  3  7  11

In [9]:
df1

a  b   c   d
A  0  1   2   3
B  4  5   6   7
C  8  9  10  11

### 2.通过索引获取列数据

In [14]:
df2['A']

a    0
b    1
c    2
d    3
Name: A, dtype: int32

In [17]:
#获取的每一列属于Series数据类型
print(type(df2['B']))

<class 'pandas.core.series.Series'>


In [18]:
df1['a']

A    0
B    4
C    8
Name: a, dtype: int32

### 3.增加列数据

In [20]:
#增加列是直接赋值即可。赋值时使用列索引。
df1['e']=[7,8,9]

In [21]:
df1

a  b   c   d  e
A  0  1   2   3  7
B  4  5   6   7  8
C  8  9  10  11  9

### 4.删除列

In [22]:
#使用del命令删除
del(df1['e'])

In [23]:
df1

a  b   c   d
A  0  1   2   3
B  4  5   6   7
C  8  9  10  11