## Pandas-数据便捷的连接方式

内容介绍:

In [2]:
import numpy as np
import pandas as pd

In [4]:
# 示例数据
df01 = pd.DataFrame(np.random.randint(0,9,size=(4,3)),columns=['D','E','F'])
df01['key'] = ['yy','xx','mm','snn']
df01

D  E  F  key
0  0  1  6   yy
1  2  1  6   xx
2  2  5  3   mm
3  5  0  2  snn

In [8]:
df02 = pd.DataFrame(np.random.randint(0,9,size=(4,3)),columns=['B','A','C'])
#df02['key'] = ['xx','yy','mm','nn']
df02

B  A  C
0  5  5  6
1  7  6  0
2  1  6  4
3  6  0  6

### 1.join函数的使用

* join(self, other, on=None, how='left', lsuffix='', rsuffix='', sort=False) -> 'DataFrame'
    Join columns of another DataFrame.
* 与merge函数的使用方法很类似。
* 此方法直接按照索引合并
* 合并数据的各列
* 此种情况下，如果有重叠的列，则会报错。即两个数据集都有key列即会报错。

In [10]:
# 此种情况下，如果有重叠的列，则会报错。即两个数据集都有key列即会报错。
df01.join(df02,how='outer')

D  E  F  key  B  A  C
0  0  1  6   yy  5  5  6
1  2  1  6   xx  7  6  0
2  2  5  3   mm  1  6  4
3  5  0  2  snn  6  0  6

### 2.另一种数据合并方式：concate

沿轴方向合并数据

### 2.1复习numpy中数据的合并方式

In [12]:
#示例数据
arr1 = np.random.randint(0,9,size=(5,3))
arr2 = np.random.randint(0,9,size=(5,3))

In [15]:
arr1

array([[2, 3, 3],
       [6, 7, 7],
       [8, 3, 0],
       [2, 5, 2],
       [4, 6, 1]])

In [16]:
arr2

array([[5, 6, 4],
       [0, 2, 1],
       [7, 7, 8],
       [6, 4, 2],
       [5, 6, 5]])

In [19]:
#numpy默认的合并方式，按照0轴合并
np.concatenate([arr1,arr2,])

array([[2, 3, 3],
       [6, 7, 7],
       [8, 3, 0],
       [2, 5, 2],
       [4, 6, 1],
       [5, 6, 4],
       [0, 2, 1],
       [7, 7, 8],
       [6, 4, 2],
       [5, 6, 5]])

In [20]:
#主动设置axis参数，按照1轴合并
np.concatenate([arr1,arr2,],axis=1)

array([[2, 3, 3, 5, 6, 4],
       [6, 7, 7, 0, 2, 1],
       [8, 3, 0, 7, 7, 8],
       [2, 5, 2, 6, 4, 2],
       [4, 6, 1, 5, 6, 5]])

### 2.2 pandas中的concate合并方式

* 注意指定轴方向，默认为axis=0
* join指定合并方式，默认为outer
* Series合并时查看行索引有无重复

In [21]:
df01

D  E  F  key
0  0  1  6   yy
1  2  1  6   xx
2  2  5  3   mm
3  5  0  2  snn

In [23]:
df02

B  A  C
0  5  5  6
1  7  6  0
2  1  6  4
3  6  0  6

In [24]:
#默认按照列合并(即列方向上相加),默认的axis=0,即0轴合并
pd.concat([df01,df02])

D    E    F  key    B    A    C
0  0.0  1.0  6.0   yy  NaN  NaN  NaN
1  2.0  1.0  6.0   xx  NaN  NaN  NaN
2  2.0  5.0  3.0   mm  NaN  NaN  NaN
3  5.0  0.0  2.0  snn  NaN  NaN  NaN
0  NaN  NaN  NaN  NaN  5.0  5.0  6.0
1  NaN  NaN  NaN  NaN  7.0  6.0  0.0
2  NaN  NaN  NaN  NaN  1.0  6.0  4.0
3  NaN  NaN  NaN  NaN  6.0  0.0  6.0

In [26]:
#指定合并方向
pd.concat([df01,df02],axis=1)

D  E  F  key  B  A  C
0  0  1  6   yy  5  5  6
1  2  1  6   xx  7  6  0
2  2  5  3   mm  1  6  4
3  5  0  2  snn  6  0  6

In [31]:
#使用列数据相同时的情况
df03 = pd.DataFrame(np.random.randint(0,9,size=(5,3)),columns=df02.columns)
df03

B  A  C
0  7  3  1
1  0  8  8
2  1  8  5
3  4  1  4
4  8  5  0

In [34]:
#默认连接行
pd.concat([df02,df03])

B  A  C
0  5  5  6
1  7  6  0
2  1  6  4
3  6  0  6
0  7  3  1
1  0  8  8
2  1  8  5
3  4  1  4
4  8  5  0

In [35]:
#axis=1,连接列
pd.concat([df02,df03],axis=1)

B    A    C  B  A  C
0  5.0  5.0  6.0  7  3  1
1  7.0  6.0  0.0  0  8  8
2  1.0  6.0  4.0  1  8  5
3  6.0  0.0  6.0  4  1  4
4  NaN  NaN  NaN  8  5  0

### 3.

In [11]:
help(pd.DataFrame.join)

Help on function join in module pandas.core.frame:

join(self, other, on=None, how='left', lsuffix='', rsuffix='', sort=False) -> 'DataFrame'
    Join columns of another DataFrame.
    
    Join columns with `other` DataFrame either on index or on a key
    column. Efficiently join multiple DataFrame objects by index at once by
    passing a list.
    
    Parameters
    ----------
    other : DataFrame, Series, or list of DataFrame
        Index should be similar to one of the columns in this one. If a
        Series is passed, its name attribute must be set, and that will be
        used as the column name in the resulting joined DataFrame.
    on : str, list of str, or array-like, optional
        Column or index level name(s) in the caller to join on the index
        in `other`, otherwise joins index-on-index. If multiple
        values given, the `other` DataFrame must have a MultiIndex. Can
        pass an array as the join key if it is not already contained in
        the calli