## ndarray数组的属性

In [2]:
import numpy as np

In [3]:
d = np.arange(0,100,20,dtype=np.float32)
d

array([ 0., 20., 40., 60., 80.], dtype=float32)

1. ndarray.ndim函数获取数组的维度

In [5]:
d.ndim

1

In [7]:
d2 = np.random.randint(0,9,size=(2,3))
d2

array([[7, 0, 7],
       [2, 0, 5]])

In [9]:
d2.ndim

2

2. ndarray.shape函数获取数组的形状

函数返回数组维度的元组。

In [10]:
d.shape

(5,)

In [11]:
d2.shape

(2, 3)

3. ndarray.reshape函数将数组变形

变形后的行列数需要同变形前的总数保持一致。<br>
变形过程不影响原来的数组<br>
参数是一个元组，有几个值，就是变形后的几维数组

In [12]:
d2.reshape(3,2)

array([[7, 0],
       [7, 2],
       [0, 5]])

In [14]:
d3 = np.random.randint(0,9,size=(2,3,3))
d3

array([[[4, 0, 6],
        [6, 0, 0],
        [1, 0, 7]],

       [[5, 7, 6],
        [4, 3, 6],
        [4, 7, 0]]])

In [21]:
d3.reshape(3,6)

array([[4, 0, 6, 6, 0, 0],
       [1, 0, 7, 5, 7, 6],
       [4, 3, 6, 4, 7, 0]])

In [25]:
#变成一维数组时，使用元组参数，(n,)
print(d3.reshape(18))
print(d3.reshape((18,)))

[4 0 6 6 0 0 1 0 7 5 7 6 4 3 6 4 7 0]
[4 0 6 6 0 0 1 0 7 5 7 6 4 3 6 4 7 0]


3. ndarray.size获取数组的元素个数<br>
ndarry.itemsize获取每个元素的占用内存空间的大小，单位是字节,每个字节为8位。int32返回itemsize为4

In [27]:
d3.size

18

In [29]:
d3.itemsize

8

In [31]:
d3.dtype

dtype('int64')

In [5]:
d4 = np.arange(10**8)

In [9]:
d4.nbytes/1024**3

7.450580596923828

In [11]:
d4.dtype

dtype('int64')