## 关于numpy数据类型的演示

In [1]:
import numpy as np

In [2]:
#创建numpy数组时不指定数据类型，会自动匹配相应类型
a = np.arange(10)
print(a)
print(a.dtype)

[0 1 2 3 4 5 6 7 8 9]
int64


In [7]:
#指定int8数据类型，使用参数dtype,int8只能存储最大整数至127
b = np.array([1,2,3,4],dtype=np.int8)
print(b)
print(b.dtype)

[1 2 3 4]
int8


In [9]:
#指定float16数据类型，使用参数dtype
c = np.array([1,2,3,4],dtype=np.float16)
print(c)
print(c.dtype)

[1. 2. 3. 4.]
float16


In [13]:
#也可以制定object数据类型（或默认匹配出），对应的是python类等对象
class Person():
    def __init__(self,name,age):
        self.name = name
        self.age = age
d = np.array([Person('小名',10),Person('小刚',39)])
print(d)
print(d.dtype)

object


In [18]:
#对应python中的byte字符串类型
e = np.array(['a','b','c'],dtype='S')
print(c)
print(c.dtype)

[b'a' b'b' b'c']
|S1


In [3]:
#对应python中的unicode字符串类型。正常显示的字符串。
f = np.array(['a','b','c'],dtype='U25')
print(f)
print(f.dtype)

['a' 'b' 'c']
<U25


In [19]:
eu = e.astype('U')
print(eu)
print(eu.dtype)
print(e.dtype)

['a' 'b' 'c']
<U1
|S1
