多维数组：获取numpy数组的维度和形状

In [1]:
import numpy as np

In [2]:
#获取数组的维度-一维数组
a1=np.array([1,2,3])
print(a1.ndim)

1


In [3]:
#获取数组的维度-二维数组
a2=np.array([[1,2,3],[4,5,6]])
print(a2.ndim)

2


In [4]:
#获取数组的维度-三维数组
a3=np.array([
            [[1,2,3],
              [4,5,6]],
             
             [[7,8,9],
             [4,5,6]]
        ])
print(a3.ndim)

3


In [6]:
#获取数组ndarray的形状
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 2, 3)

In [12]:
#数组形状的变形，三维以上的数组变形为低维数组

a4 = a3.reshape(3,4)
print(a4)
print(a4.ndim)
print(a4.shape)

[[1 2 3 4]
 [5 6 7 8]
 [9 4 5 6]]
2
(3, 4)


In [13]:
#reshape中有几个值，就是几维数组。直接获取一维数组时，在参数元组中写一个数即可。
a5 = a3.reshape(12,)
print(a5)
print(a5.ndim)
print(a5.shape)

[1 2 3 4 5 6 7 8 9 4 5 6]
1
(12,)


In [14]:
#获取一维数组时，可以直接让ndarray扁平化
#使用flatten函数
a6 = a3.flatten()
print(a6)
print(a6.ndim)
print(a6.shape)

[1 2 3 4 5 6 7 8 9 4 5 6]
1
(12,)


In [15]:
#获取数组中元素的总个数的方法size
a3.size

12

In [16]:
a2.size

6

In [19]:
#获取数组中每个单元占用的字节数.每个字节占8位，返回值是8对应的int64数据格式
print(a3.itemsize)
print(a3.dtype)

8
int64


# 总结：
1. 数组达到三维就会很复杂，一般会把三维数组转化为二位数组计算
2. 通过ndarray.ndim可以看到数组的维度；
3. 通过ndarray.shape可以看到数组的形状，shape是一个元组，里面有几个元素代表几维数组
4. 通过ndarray.reshape可以修改数组的形状。条件只有一个，修改前后的数据总数保持一致
5. reshape不会修改原来数组，只是将修改后的数据返回