## numpy数组的索引和切片方法

ndarrays可以使用标准Python x[obj]语法对其进行索引 ，其中 x 是数组， obj 是选择。有三种可用的索引：字段访问，基本切片，高级索引。哪一个发生取决于 obj 

In [21]:
import numpy as np

In [3]:
a1 = np.array([1,2,3,4,5])

##  1.一维数组索引的方法，同python的列表一致

In [7]:
print(a1[0])
print(a1[1:4])

1
[2 3 4]


In [12]:
# 获取数组中多个不连续数据。python列表没有获取多个不连续数据的方法。
a1[[1,4]]

array([2, 5])

## 2. 多维数组的索引和切片
也是通过中括号进行索引和切片。在中括号中使用逗号分隔，逗号前面是行，逗号后面是列；
如果是多维数组中只有一个值，那么这个值就是行。获取列数据的化，逗号前面加:,后面是列号

In [14]:
a2 = np.random.randint(0,10,size=(4,6))
print(a2)

[[8 8 9 2 3 4]
 [1 3 4 8 6 9]
 [2 9 3 6 1 7]
 [9 0 8 6 7 7]]


In [11]:
#获取二维数组的某一行
a2[0]

array([6, 6, 7, 2, 9, 9])

In [14]:
#获取二维数组的某几行（多行连续）
a2[1:3]

array([[4, 9, 0, 7, 6, 7],
       [6, 4, 2, 8, 3, 3]])

In [18]:
#获取二维数组多行不连续
a2[[0,1,2]]

array([[6, 6, 7, 2, 9, 9],
       [4, 9, 0, 7, 6, 7],
       [6, 4, 2, 8, 3, 3]])

In [9]:
#此处和python的列表索引存在区别。使用,号后，numpy的索引较为简洁。
#一级[]中的,区分行列。行内、列内用[]包括即可。
a2[1,1]

9

In [19]:
#多行多列切片,不连续
a2[[1,2],[4,5]]

array([6, 3])

In [23]:
#多行多列切片，连续
a2[1:3,3:5]

array([[7, 6],
       [8, 3]])

In [26]:
#多行多列，连续不连续的情况对比
print(a2[[1,3],[3,5]])
print(a2[1:3,3:5])

[7 2]
[[7 6]
 [8 3]]


In [15]:
#当获取整列时，行位置只填写:表示全选
a2[:,2]

array([9, 4, 3, 8])

## 3.numpy 布尔索引

用于数字提取很方便。理论上，布尔索引是一种高级索引，与基本索引和切片返回的视图不同，布尔索引直接返回新的数组。

In [22]:
a3 = np.arange(24).reshape((4,6))
print(a3)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [24]:
a3[a3>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [25]:
d = a3[a3>5]
print(d)
d[3]=99
print('*'*20)
print(a3)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
********************
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


可以使用多种条件形成布尔值,可以用&代表且，|代表或。多个条件用()括起来。

In [40]:
#获取<5,>10的值
a3[(a3<5)|(a3>15)]

array([ 0,  1,  2,  3,  4, 16, 17, 18, 19, 20, 21, 22, 23])

## 4.使用函数替换数组中的数据

In [16]:
a4 = np.random.randint(0,10,size=(3,5))
print(a4)

[[3 0 7 6 0]
 [5 8 7 4 1]
 [1 5 0 9 5]]


In [45]:
#将某一行的数据替换为固定数据
a4[1]=0
print(a4)

[[2 1 1 4 2]
 [0 0 0 0 0]
 [6 2 1 4 5]]


In [47]:
#将某一行替换为固定的数组
a4[1]=[1,2,3,4,5]
print(a4)

[[2 1 1 4 2]
 [1 2 3 4 5]
 [6 2 1 4 5]]


In [49]:
#使用条件索引替换，例如小于3的数据全部替换为0
a4[a4<3]=0
print(a4)

[[0 0 0 4 0]
 [0 0 3 4 5]
 [6 0 0 4 5]]


## 5. np.where函数的使用

where(condition, [x, y])：

Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to bebroadcastable to some shape.
    
    Returns
    -------
    out : ndarray。返回一个新的ndarray数组

In [19]:
#使用where函数定位，在输入两个参数，符合条件的变为的值和不符合条件的变为的值。
result = np.where(a4<5,0,1)
print(result)

[[0 0 1 1 0]
 [1 1 1 0 0]
 [0 1 0 1 1]]


In [20]:
a4

array([[3, 0, 7, 6, 0],
       [5, 8, 7, 4, 1],
       [1, 5, 0, 9, 5]])

In [18]:
help(np.where)

Help on function where in module numpy:

where(...)
    where(condition, [x, y])
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called when x and y