## 数组的广播机制

In [2]:
import numpy as np

In [5]:
a1 = np.random.randint(0,9,size=(4,6))
print(a1)

[[7 2 8 4 5 6]
 [4 3 0 4 4 5]
 [1 6 0 5 7 2]
 [2 2 3 7 2 2]]


In [6]:
#数组直接乘以某数可以让所有元素都乘以某数
a2 = a1*2
print(a2)

[[14  4 16  8 10 12]
 [ 8  6  0  8  8 10]
 [ 2 12  0 10 14  4]
 [ 4  4  6 14  4  4]]


In [10]:
a3 = np.random.randint(0,9,size=(4,6))
print(a3)

[[1 7 7 6 5 8]
 [7 6 7 0 5 0]
 [6 5 4 3 7 5]
 [7 4 1 0 2 6]]


In [11]:
#形状一致可以直接参与运算
a1+a3

array([[ 8,  9, 15, 10, 10, 14],
       [11,  9,  7,  4,  9,  5],
       [ 7, 11,  4,  8, 14,  7],
       [ 9,  6,  4,  7,  4,  8]])

In [15]:
a4=np.random.randint(0,5,size=(3,4))
a4

array([[3, 1, 4, 0],
       [2, 1, 4, 2],
       [1, 2, 4, 0]])

In [14]:
#形状不一致不能直接相加运算。
a1+a4

ValueError: operands could not be broadcast together with shapes (4,6) (3,4) 

In [17]:
#但行数相同，列数不同的可以运算。每行的一个数据加到每一行的各个数字上。限于只有一列。
a5=np.random.randint(0,5,size=(3,1))
a5

array([[4],
       [4],
       [3]])

In [18]:
a4+a5

array([[7, 5, 8, 4],
       [6, 5, 8, 6],
       [4, 5, 7, 3]])

In [21]:
#列数相同，行数不同的化，单一行的数据加(乘)到每一行上。限于一行。
a6 = np.random.randint(0,5,size=(1,4))
a6

array([[2, 3, 2, 4]])

In [23]:
a4*a6

array([[6, 3, 8, 0],
       [4, 3, 8, 8],
       [2, 6, 8, 0]])

### 三维数组也可以相加，需要符合广播原则

## 广播的总结
1. 数组直接和数字广播运算没有问题。
2. 两个shape相同的数组可以直接运算。(包括加减乘除)
3. 两个shape不同的数组是否可以直接运算，取决于是否满足广播原则。
4. 广播的原则:如果两个数组的后缘维度(即从末尾开始算起的维度)的轴长度相符或其中一方的长度为1，则认为他们的广播是兼容的。
    广播会在缺失和（或）长度为1的维度上进行。