## numpy数组形状的操纵

In [1]:
import numpy as np

1. reshape不会修改原数组

In [4]:
a1 = np.random.randint(0,6,size=(2,6))
a1

array([[2, 5, 4, 5, 5, 2],
       [4, 4, 3, 1, 4, 4]])

In [5]:
a1.reshape((3,4))

array([[2, 5, 4, 5],
       [5, 2, 4, 4],
       [3, 1, 4, 4]])

In [6]:
#使用reshape后的原数组a1的形状并没有改变
a1

array([[2, 5, 4, 5, 5, 2],
       [4, 4, 3, 1, 4, 4]])

2. 使用resize函数，会改变原数组

In [7]:
a2 = np.random.randint(0,6,size=(2,6))
a2

array([[5, 0, 1, 2, 4, 3],
       [1, 4, 0, 5, 4, 2]])

In [8]:
#执行后没有返回任何值
a2.resize((3,4))

In [10]:
a2

array([[5, 0, 1, 2],
       [4, 3, 1, 4],
       [0, 5, 4, 2]])

3. flatten和ravel函数

* faltten和ravel将数组转换为一维数组.两者返回值的操作不一致。

In [11]:
a3 = np.random.randint(0,6,size=(3,5))
a3

array([[5, 1, 2, 0, 2],
       [0, 2, 4, 0, 3],
       [3, 0, 3, 2, 5]])

In [23]:
a4 = a3.flatten()
a4

array([100,   1,   2,   0,   2,   0,   2,   4,   0,   3,   3,   0,   3,
         2,   5])

In [18]:
#执行flatten之后原数组没有改变
a3

array([[5, 1, 2, 0, 2],
       [0, 2, 4, 0, 3],
       [3, 0, 3, 2, 5]])

In [20]:
a5 = a3.ravel()
a5

array([5, 1, 2, 0, 2, 0, 2, 4, 0, 3, 3, 0, 3, 2, 5])

In [21]:
a3

array([[5, 1, 2, 0, 2],
       [0, 2, 4, 0, 3],
       [3, 0, 3, 2, 5]])

In [ ]:
#两方法的区别在于拷贝.ravel实际上是一种视图，修改视图中的值就会修改原数组中的值。flatten就不会存在这个问题。

In [24]:
a5[0]=100
print(a5)
print(a3)

[100   1   2   0   2   0   2   4   0   3   3   0   3   2   5]
[[100   1   2   0   2]
 [  0   2   4   0   3]
 [  3   0   3   2   5]]


## 总结
1. reshape和resize都可以重新定义形状。resize直接修改数组本身，reshape不能。
2. flatten和ravel都能将数组变成一维数组，并且变形本身不会修改原数组。两者的区别在于，flatten的返回值修改某一个值也不会修改原数组。但ravel本质上是一种视图(View),修改某一个值会导致原数组的修改。