## 一、讲述数组叠加、拼合等

In [2]:
import numpy as np

1. 垂直方向的叠加,使用np.vstack方法。将数字在垂直方向叠加。将数据加在列数据后面，增加的方向判断是横向还是纵向。

In [9]:
vstack1=np.random.randint(0,9,size=(3,5))
print(vstack1)
print('*'*20)
vstack2=np.random.randint(0,9,size=(1,5))
print(vstack2)

[[0 6 5 0 1]
 [7 5 4 2 6]
 [8 2 4 7 7]]
********************
[[5 8 3 7 5]]


In [15]:
vstack3=np.vstack([vstack1,vstack2])
vstack3

array([[0, 6, 5, 0, 1],
       [7, 5, 4, 2, 6],
       [8, 2, 4, 7, 7],
       [5, 8, 3, 7, 5]])

In [17]:
v4=np.concatenate([vstack1,vstack2],0)
v4

array([[0, 6, 5, 0, 1],
       [7, 5, 4, 2, 6],
       [8, 2, 4, 7, 7],
       [5, 8, 3, 7, 5]])

2. 使用hstack方法，将数组按照水平方向叠加。即将数据加在每列数据的水平方向上。

In [12]:
hstack1=np.random.randint(0,9,size=(3,5))
print(hstack1)
print('*'*20)
hstack2=np.random.randint(0,9,size=(3,1))
print(hstack2)

[[6 2 7 1 6]
 [0 4 8 8 6]
 [0 1 6 2 1]]
********************
[[1]
 [2]
 [5]]


In [18]:
hstack3 = np.hstack([hstack1,hstack2])
hstack3

array([[6, 2, 7, 1, 6, 1],
       [0, 4, 8, 8, 6, 2],
       [0, 1, 6, 2, 1, 5]])

In [20]:
h4=np.concatenate([hstack1,hstack2],1)
h4

array([[6, 2, 7, 1, 6, 1],
       [0, 4, 8, 8, 6, 2],
       [0, 1, 6, 2, 1, 5]])

3. concatenate([], axis)，手动指定行列的数组叠加。axis是指定行还是列。0为垂直方向叠加（加行），1为水平方向上的叠加（加列）。
两种情况与vstack和hstack等效。

In [1]:
# concatenate中axis参数的特殊情形:none时，即不指定横向还是纵向，那么会拼接成一维数组。
h5=np.concatenate([hstack1,hstack2],None)
h5

NameError: name 'np' is not defined

## 二、numpy数组的切割

1. hspilt方法切割，水平切割(减少的方向判断，或者切割刀的排列方向上)

In [5]:
hs1 = np.arange(16).reshape(4,4)
hs1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
#第二个参数是切割出来的数量，必须能切割出来整数，否则报错
np.hsplit(hs1,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [8]:
#切割行为不改变原有的数组
hs1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
#指定切割点，需要是第二个参数是元组，元组中包含切割点

In [10]:
#0列中间切割，1-3列中间切割。列标含前不含后。
np.hsplit(hs1,(1,3))

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

2. vsplit(ndarray,splitnum)方法纵向切割，也需要splitnum参数能够被总行数整除。切割减少的数组判断方向(或者切割刀的排列方向上判断)。
或者splitnum为元组标识行号。

In [11]:
vs1=np.random.randint(0,9,size=(6,3))
vs1

array([[4, 5, 8],
       [8, 2, 6],
       [6, 1, 5],
       [2, 0, 0],
       [6, 2, 2],
       [3, 1, 0]])

In [12]:
np.vsplit(vs1,3)

[array([[4, 5, 8],
        [8, 2, 6]]),
 array([[6, 1, 5],
        [2, 0, 0]]),
 array([[6, 2, 2],
        [3, 1, 0]])]

In [13]:
#元组标识的行号同样含前不含后。
np.vsplit(vs1,(1,4))

[array([[4, 5, 8]]),
 array([[8, 2, 6],
        [6, 1, 5],
        [2, 0, 0]]),
 array([[6, 2, 2],
        [3, 1, 0]])]

3. split/array_split,手动参数输入后区分行列切割

In [16]:
#参数1属于横向切割(刀排列的方向)
np.split(hs1,2,1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [18]:
#最后一个参数1属于横向切割(刀排列的方向),切割数量也可元组参数切割
np.split(hs1,(1,3),1)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [20]:
#最后一个参数0属于纵向切割(刀排列的方向)
np.split(hs1,2,0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

## 三、数组的转置，行变列，列变行

1. 使用T方法进行转置

In [22]:
t1 = np.random.randint(0,9,size=(3,5))
t1

array([[6, 4, 1, 8, 3],
       [5, 7, 8, 8, 2],
       [2, 5, 4, 2, 8]])

In [24]:
t1.T

array([[6, 5, 2],
       [4, 7, 5],
       [1, 8, 4],
       [8, 8, 2],
       [3, 2, 8]])

In [26]:
#转置不改变原数组
t1

array([[6, 4, 1, 8, 3],
       [5, 7, 8, 8, 2],
       [2, 5, 4, 2, 8]])

In [ ]:
2. 使用transpose进行转置。可以返回新的数组，这个数组属于视图(View)，修改后改变原来的数组本身。

In [28]:
t2 = np.random.randint(0,9,size=(2,4))
t2

array([[3, 1, 4, 5],
       [7, 2, 3, 3]])

In [30]:
t3=t2.transpose()
t3

array([[3, 7],
       [1, 2],
       [4, 3],
       [5, 3]])

In [32]:
t3[0,0]=100
print(t3)
print('*'*20)
print(t2)

[[100   7]
 [  1   2]
 [  4   3]
 [  5   3]]
********************
[[100   1   4   5]
 [  7   2   3   3]]


### 矩阵转置的方法总结
1. 可以使用ndarray.T或者是ndarrat.transpose()进行
2. ndarray.T转置方法，不改变原有的数组，同时变换之后的修改单个元素也不改变原来的数组。
3. ndarray.transpose()方法属于一种视图，本身转置完成后不改变原有数组。修改单个元素会修改原有的数组。