## numpy的拷贝、深拷贝和浅拷贝
视频讲解比较好，不明之处可再次观看。

In [2]:
import numpy as np

In [7]:
c1 = np.arange(10)
c1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

1. 不拷贝，下面这种情况两个变量指向一个数组

In [16]:
#下面的情况是简单的赋值，不进行拷贝。原来的栈区变量取了个别名。
a = c1
print(a)
print('*'*20)
print(a is c1)

[0 1 2 3 4 5 6 7 8 9]
********************
True


In [17]:
print(id(a))
print(id(c1))

140281887750544
140281887750544


2. 视图(View)或者浅拷贝，只在栈区拷贝了变量名至另外一个。

In [25]:
c2 = np.arange(12)
c2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
b = c2.view()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
print(c2 is b)

False


In [28]:
#这里验证view函数出现了深拷贝的特征????修改view后的数组，并没有改变原数组。
b[0]=100
print(c2)
print('*'*20)
print(b)

[100   1   2   3   4   5   6   7   8   9  10  11]
********************
[100   1   2   3   4   5   6   7   8   9  10  11]


In [29]:
print(id(c2))
print(id(b))

140281887925808
140281887925136


In [19]:
help(id)

Help on built-in function id in module builtins:

id(obj, /)
    Return the identity of an object.
    
    This is guaranteed to be unique among simultaneously existing objects.
    (CPython uses the object's memory address.)



3. 深拷贝。copy()函数，这里与python的深拷贝保持一致。

In [21]:
c3 = np.arange(11)
c3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
d = c3.copy()
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
print(c3 is d)

False


In [24]:
d[0]=100
print(c3)
print('*'*20)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10]
********************
[100   1   2   3   4   5   6   7   8   9  10]


## 总结：
在数组操作中分为三种
1. 不拷贝: 只是在栈区将原来的变量重命名。
2. 浅拷贝：只拷贝指定栈区，不拷贝堆区。修改浅拷贝会影响原有的数组。
3. 深拷贝: 在堆区拷贝了一份新的数据。修改拷贝的数据后，不会影响原来的数组数据。
* 概念理解(个人理解，并不准确)：
* 栈区、和堆区出自C语言，只一种内存存储的方式。栈区存储的是变量名称相关内容，可以快速运算。堆区储存变量的真实数据，数据量较大，运算起来相对较慢。
* 大部分的数据都有这几类拷贝的概念。针对数据的方法也存在深浅拷贝等不同方法。
* 可以使用python中的id()函数，查看数据的原是记载地址。