## numpy方法读取csv文件(及其他文本文件)

In [1]:
import numpy as np

In [12]:
a = np.random.randint(40,100,size=(5,5))
print(a)

[[42 84 79 77 68]
 [90 60 52 71 91]
 [46 58 95 89 66]
 [63 40 43 53 95]
 [62 67 77 63 62]]


1. 保存csv文件的方法，使用numpy.savetxt()。可以使用help(np.savetxt)查看详细的使用方法。

numpy.savetxt(fname, X, fmt='%.18e', delimiter=' ',......）

Parameters
    ----------
    fname : filename or file handle
    X : 1D or 2D array_like
        Data to be saved to a text file.
    fmt : str or sequence of strs, optional
    delimiter : str, optional
        String or character separating columns.
    header : str, optional。加入数据的标题。
    comments : str, optional.标题开始前的字符，默认为Default: '# '
    fmt : str or sequence of strs, optional.'%d'表示整型数据

In [18]:
#np.savetxt()函数的实际使用
np.savetxt('nprandom.csv',a,fmt='%d',delimiter=',',header='a,b,c,d,e',comments='')

2. 读取csv文件使用np.loadtxt()方法。可以使用help(np.loadtxt)查看参数说明。

Parameters
    ----------
    fname : file, str, or pathlib.Path
    dtype : data-type, optional。读取出数据的数据类型。
    comments : str or sequence of str, optional
    delimiter : str, optional。被读取文件的分割符
    skiprows : int, optional。跳过多少行转换数据类型。

In [19]:
#np.loadtxt()函数的实际使用
b=np.loadtxt('nprandom.csv',dtype=np.int8,delimiter=',',skiprows=1)
print(b)

[[42 84 79 77 68]
 [90 60 52 71 91]
 [46 58 95 89 66]
 [63 40 43 53 95]
 [62 67 77 63 62]]


3. numpy特有的存储数据方法。numpy.load(),numpy.save().

In [3]:
arr=np.random.randint(0,9,size=(3,4))
arr

array([[1, 1, 0, 5],
       [7, 8, 4, 2],
       [2, 6, 6, 2]])

In [6]:
#np.save()函数将数组保存成.npy格式的文件。
'''
save(file, arr, allow_pickle=True, fix_imports=True)
    Save an array to a binary file in NumPy ``.npy`` format.
    
    Parameters
    ----------
    file : file, str, or pathlib.Path
    arr : array_like
        Array data to be saved.
'''
#文件名参数不需要写文件后缀名，函数在保存文件时自动补全。
np.save('numpy_doc',arr)

In [9]:
#np.load()函数从.npy文件中读取数组数据
'''
load(file, mmap_mode=None, allow_pickle=False, fix_imports=True, encoding='ASCII')
    Load arrays or pickled objects from ``.npy``, ``.npz`` or pickled files.  
    Parameters
    ----------
    file : file-like object, string, or pathlib.Path
        The file to read. File-like objects must support the
        ``seek()`` and ``read()`` methods. Pickled files require that the
        file-like object support the ``readline()`` method as well.
'''
arr1=np.load('numpy_doc.npy')
arr1

array([[1, 1, 0, 5],
       [7, 8, 4, 2],
       [2, 6, 6, 2]])

In [2]:
help(np.savetxt)

Help on function savetxt in module numpy:

savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)
    Save an array to a text file.
    
    Parameters
    ----------
    fname : filename or file handle
        If the filename ends in ``.gz``, the file is automatically saved in
        compressed gzip format.  `loadtxt` understands gzipped files
        transparently.
    X : 1D or 2D array_like
        Data to be saved to a text file.
    fmt : str or sequence of strs, optional
        A single format (%10.5f), a sequence of formats, or a
        multi-format string, e.g. 'Iteration %d -- %10.5f', in which
        case `delimiter` is ignored. For complex `X`, the legal options
        for `fmt` are:
    
        * a single specifier, `fmt='%.4e'`, resulting in numbers formatted
          like `' (%s+%sj)' % (fmt, fmt)`
        * a full string specifying every real and imaginary part, e.g.
          `' %.4e %+.4ej %.4e %+.4ej %.4

## 总结：
1. numpy.save(),numpy.load()函数可以保存、读取所有的ndarry数据，包括任一维度的数据。
2. numpy.savetxt(),numpy.loadtxt()函数可以读取、保存所有一维和二维的数组数据，更高维度的不可以保存。