## random函数讲解

In [2]:
import numpy as np

### 1. numpy.random.seed函数和random.rand()函数
numpy下的隨機數屬於偽隨機數，即给定种子下生成的随机数是相同的

In [26]:
#random.rand()生成给定维度的数组。不给定维度时生成一个python浮点数。
np.random.rand()

0.34556072704304774

In [27]:
#可以生成多维数组
np.random.rand(2,3)

array([[0.39676747, 0.53881673, 0.41919451],
       [0.6852195 , 0.20445225, 0.87811744]])

In [28]:
#设置seed后随机数不变(所有平台都不变)
#没有设置时，随机数产生的种子是根据系统的时间戳生成的
np.random.seed(1)
np.random.rand()

0.417022004702574

### 2. random.randn标准正态分布的随机函数

### 3. random.randint生成整型随机数

In [29]:
'''
randint(low, high=None, size=None, dtype=int)
low,high两参数给定随即区间。
size=(a,b),此参数给定生成数组的维度情况。
dtype参数确定数据类型，只能在int数据类型中选择，否则报错。
'''
#生成两行三列的随机数组，每个值在0-9的整数。
np.random.randint(0,9,size=(2,3))

array([[8, 5, 0],
       [0, 1, 7]])

### 4.random.choice()函数

choice(a, size=None, replace=True, p=None)
a:数据源，可以是一个数组(需要一维)，也可以是一个数组表示生成0到这个数字的随机选择数。
size:选择数据后生成数据的维度。

In [35]:
# choice函数在序列中随即选择几个数字组成行列数组
data = np.random.randint(0,9,size=(10,))
data

array([6, 1, 0, 1, 8, 8, 3, 8, 7, 3])

In [37]:
#随机选取生成一维数组
np.random.choice(data,3)

array([3, 1, 8])

In [40]:
#随机选择生成二维数组
np.random.choice(data,size=(2,3))

array([[0, 6, 8],
       [3, 0, 8]])

### 5.random.shuffle()把原来元素的位置打乱

shuffle(x)
x:需要打乱的数组

This function only shuffles the array along the first axis of a multi-dimensional array. 

这个函数只能打乱包含在多维数组中的第一维度。

此函数直接更新数组。

In [43]:
data2 = np.random.randint(0,9,size=(3,4))
data2

array([[2, 7, 7, 7],
       [3, 0, 8, 7],
       [7, 1, 1, 3]])

In [47]:
#打乱二维数组，只是打乱了不同块的顺序
np.random.shuffle(data2)
data2

array([[7, 1, 1, 3],
       [2, 7, 7, 7],
       [3, 0, 8, 7]])

In [48]:
data3=np.arange(9)
data3

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
#一维数组是打乱内部数字
np.random.shuffle(data3)
data3

array([8, 0, 1, 7, 6, 5, 3, 4, 2])

In [41]:
help(np.random.shuffle)

Help on built-in function shuffle:

shuffle(...) method of numpy.random.mtrand.RandomState instance
    shuffle(x)
    
    Modify a sequence in-place by shuffling its contents.
    
    This function only shuffles the array along the first axis of a
    multi-dimensional array. The order of sub-arrays is changed but
    their contents remains the same.
    
    .. note::
        New code should use the ``shuffle`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    x : ndarray or MutableSequence
        The array, list or mutable sequence to be shuffled.
    
    Returns
    -------
    None
    
    See Also
    --------
    Generator.shuffle: which should be used for new code.
    
    Examples
    --------
    >>> arr = np.arange(10)
    >>> np.random.shuffle(arr)
    >>> arr
    [1 7 5 2 9 4 3 6 0 8] # random
    
    Multi-dimensional arrays are only shuffled along the first axis:
    
    >>> ar