## numpy axis轴的理解

In [1]:
import numpy as np

In [7]:
data = np.arange(18).reshape(3,2,3)
data

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [5]:
#数据的维度
data.ndim

3

In [6]:
data.shape

(3, 3, 3)

### 1.数组最外面的括号代表axis=0,依次往里面的括号对应的axis的计数依次加1

### 2.针对数组的函数操作，针对轴下一级的直接子原组分别进行操作。

In [21]:
data1 = np.arange(4).reshape(2,2)
data1

array([[0, 1],
       [2, 3]])

## 3.相关函数的实践

In [17]:
#如果axis=0时，数据根据总数组下一级[0,1]\[2,3]中的第一个元素分别相加，第二个元素分别相加，最后得出结果。
data1.sum(axis=0)

array([2, 4])

In [19]:
#如果指定axis=1则，[0,1]下面的数组(元素)即0,1两个相加得出结果，[2,3]中的两个元素相加得出结果。
data1.sum(axis=1)

array([1, 5])

In [23]:
#max函数,axis=0
data1.max(axis=0)

array([2, 3])

In [25]:
#max函数,axis=1
data1.max(axis=1)

array([1, 3])

In [30]:
#delete函数的用法
data2 = np.random.randint(0,9,size=(3,5))
data2

array([[4, 8, 8, 2, 1],
       [0, 0, 0, 4, 8],
       [0, 4, 4, 1, 1]])

* delete函数删除数组中指定的axis中的本层数组。
* 此处与其他函数不同

In [32]:
np.delete(data2,0,axis=1)

array([[8, 8, 2, 1],
       [0, 0, 4, 8],
       [4, 4, 1, 1]])

In [33]:
data2

array([[4, 8, 8, 2, 1],
       [0, 0, 0, 4, 8],
       [0, 4, 4, 1, 1]])