## numpy函数的讲解-二元函数

numpy函数分为一元函数、二元函数和聚合函数。

2. 二元函数在使用时除了传递数组，还需要传递其他参数。

 * 二元函数都是表示一些两组数据之间运算的函数。
 * 数学运算符本质上是这些函数的语法糖。
 * 理解二元函数需要结合numpy的广播特性

|序号|  函数   | | 描述  |
|:----:|  :----  | | ----:  |
|1| np.add  | | 加法运算(2+3=5)，两个数组相加，相当于运算符+ |
|2| np.subtrsct |  | 减法运算(6-3=3)：相当于运算符- |
|3| np.negative |  | 求负数运算(2->-2)，相当于加个- |
|4| np.multiply |  | 乘法运算(2\*3=6) ，相当于运算符*|
|5|np.divide |  | 除法运算(6/3=2),相当于运算符/ |
|6| np.divide_floor |  | 相当于// |
|7| np.greater/...... |  | 获取大于某数的数据，相当于>,<,>=,<=,!=的函数表达式 |
|8| np.logic_and |  | &的函数表达式 |
|9| np.logic_or |  | \|的函数表达式 |

In [1]:
import numpy as np

In [5]:
d1=np.random.randint(0,9,size=(3,5))
print(d1)
print('*'*20)
d2=np.random.randint(0,9,size=(3,5))
print(d2)

[[2 1 7 8 0]
 [0 1 3 3 4]
 [6 2 8 1 0]]
********************
[[2 5 3 3 1]
 [8 5 1 3 1]
 [1 3 2 6 0]]


In [11]:
#np.add相当于两个数组的+
print(np.add(d1,d2))
print('*'*20)
print(d1+d2)

[[ 4  6 10 11  1]
 [ 8  6  4  6  5]
 [ 7  5 10  7  0]]
********************
[[ 4  6 10 11  1]
 [ 8  6  4  6  5]
 [ 7  5 10  7  0]]


In [13]:
#可以使用数组加常数的方法进行，此时同数组广播的方法一致。
print(np.add(d1,2))
print('*'*20)
print(d1+2)

[[ 4  3  9 10  2]
 [ 2  3  5  5  6]
 [ 8  4 10  3  2]]
********************
[[ 4  3  9 10  2]
 [ 2  3  5  5  6]
 [ 8  4 10  3  2]]


In [16]:
#np.greater(),>操作符
#实际上操作符和操作符函数通用，一般使用操作符比较简洁
print(d1)
print('*'*20)
print(d1[d1>3])
print('*'*20)
print(d1[np.greater(d1,3)])

[[2 1 7 8 0]
 [0 1 3 3 4]
 [6 2 8 1 0]]
********************
[7 8 4 6 8]
********************
[7 8 4 6 8]
