## numpy函数的讲解-聚合函数

numpy函数分为一元函数、二元函数和聚合函数。

3. 聚合函数：求数组的总和、平均值、排序等

 * 理解聚合函数需要理解numpy的axis轴特性。
 * numpy.sum()和ndarray.sum()函数可以通用，除了在使用numpy.sum()计算pyhton序列的数组时。

|序号||  函数   | | 安全函数| | 描述  |
|----||  :----  | | :----  |  | ----:  |
|1|| np.sum | | np.nansum | | 计算元素的和。np.nansum是一种安全算法，排除nan值之后的相加 |
|2||  np.prod | | np.nanprod  |  | 计算元素的乘积  |
|3||  np.mean | | np.nanmean  |  |  计算元素的平均值 |
|4||  np.stu | | np.nanstu  |  | 计算元素的标准差  |
|5|| np.var  | |  np.nanstu |  |  计算元素的方差 |
|6||  np.min | |  np.nanmin |  |  计算元素的最小值 |
|7||  np.max | | np.nanmax  |  |  计算元素的最大值 |
|8|| np.argmin  | |  np.nanargmin |  |  找出最小值元素的索引|
|9||  np.argmax | |  np.nanargmax |  |  找出最大值元素的索引 |
|10|| np.median  | |  np.nanmedian |  | 计算元素的中位数  |

In [2]:
import numpy as np

In [3]:
d1 = np.random.randint(0,9,size=(2,3))
d1

array([[8, 7, 3],
       [0, 0, 6]])

1. np.sum()函数。等同于ndarry.sum()。

In [4]:
# 当不输入axis参数时，全部数据求和
d1.sum()

24

In [5]:
#使用np.sum需要指定axis参数的值，即求和的轴
np.sum(d1,axis=0)

array([8, 7, 9])

In [6]:
#使用np.sum需要指定axis参数的值，即求和的轴
np.sum(d1,axis=1)

array([18,  6])

2. np.prod()函数。等同于ndarry.prod()函数，求数据乘积。

In [7]:
d2=np.random.randint(1,9,size=(2,3))
d2

array([[6, 1, 2],
       [6, 1, 4]])

In [8]:
#求积np.prod()，不输入轴时是全部数据的乘积。
np.prod(d2)

288

In [24]:
d2.prod(axis=0)

array([2, 2, 8])

3. 求平均值函数np.mean()

In [25]:
d3=np.random.randint(0,9,size=(2,3))
d3

array([[1, 4, 6],
       [7, 0, 3]])

In [26]:
np.mean(d3)

3.5

In [27]:
np.mean(d3,axis=0)

array([4. , 2. , 4.5])

In [28]:
np.mean(d3,axis=1)

array([3.66666667, 3.33333333])

In [29]:
d3.mean(axis=1)

array([3.66666667, 3.33333333])

4. 求数据的标准差np.std()

In [30]:
d4=np.arange(12).reshape(3,4)
d4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
np.std(d4,axis=1)

array([1.11803399, 1.11803399, 1.11803399])

In [33]:
d4.std(axis=1)

array([1.11803399, 1.11803399, 1.11803399])

5. 求数据的方差np.var()
6. 求数据的最大值np.max()、最小值np.min()

7. 求数据的最小值索引np.argmin()、最大值的索引np.argmax()

In [34]:
d7=np.arange(12).reshape(3,4)
d7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
#当不输入axis参数时，当一维数组进行计算
np.argmin(d7)

0

In [36]:
np.argmin(d7,axis=0)

array([0, 0, 0, 0])

In [37]:
np.argmin(d7,axis=1)

array([0, 0, 0])

8. 求数据的中位数np.median

In [38]:
d8=np.random.randint(0,9,size=(2,3))
d8

array([[6, 3, 6],
       [2, 3, 6]])

In [39]:
np.median(d8)

4.5

In [40]:
np.median(d8,axis=0)

array([4., 3., 6.])

In [41]:
np.median(d8,axis=1)

array([6., 3.])

9. python内置的数学函数，同numpy的数学函数实现功能类似，但numpy的执行效率高，速度快。

In [57]:
#内置的sum函数执行时间
%time sum(np.arange(1000000))

CPU times: user 94.7 ms, sys: 1.32 ms, total: 96 ms
Wall time: 94.4 ms


499999500000

In [45]:
#np.sum()函数的计算时间
%time np.sum(np.arange(1000000))

CPU times: user 4.01 ms, sys: 0 ns, total: 4.01 ms
Wall time: 3.45 ms


499999500000

In [56]:
%%time
#计算1-1000000中间各个数字的和
s=0
for n in range(1000000):
    s+=n
print(s)

499999500000
CPU times: user 129 ms, sys: 0 ns, total: 129 ms
Wall time: 127 ms
