## numpy函数-布尔函数

numpy.any:判断是否存在真元素(任一个元素)，只要有一个为ture函数返回ture
numpy.all:判断所有的元素为真，结果返回真值ture

In [1]:
import numpy as np

In [2]:
d = np.random.randint(0,9,size=(3,5))
d

array([[6, 8, 3, 1, 7],
       [8, 4, 6, 1, 7],
       [4, 6, 3, 4, 2]])

In [3]:
np.any(d)

True

In [4]:
np.all(d)

True

In [5]:
d2=np.arange(0,9)
d2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
np.any(d2)

True

In [7]:
#ture和false的判断标准同python的基本标准:即空字符串、0、None都为flase.
np.all(d2)

False

In [11]:
#结合逻辑判断语句进行判断
#逻辑语句返回逻辑数组，之后使用函数得出结果比较快速
np.any(d>3)

True

In [10]:
d>3

array([[ True,  True, False, False,  True],
       [ True,  True,  True, False,  True],
       [ True,  True, False,  True, False]])

In [12]:
(d>3).any()

True