## numpy数组的排序

np.sort函数，数组的排序:
 * 默认是使用数组的最后一个轴进行排序
 * 比python本身的排序函数执行效率高
 * np.sort()形式排序不会改变数组本身，ndarray.sort()会改变数组本身。
 * sort()函数为从小到大排序。
 * 如果想反向排序即从大到小，可以使用其他方法，如先给排序数据加负号，再把排序后的数据加负返回号。

In [16]:
import numpy as np

1. 普通的排序函数np.sort()和ndarry.sort() 

In [8]:
d=np.random.randint(0,12,size=(3,5))
d

array([[ 5, 10,  0,  1,  7],
       [ 8,  1,  4,  0, 10],
       [ 3,  0,  2,  4, 11]])

In [9]:
#默认针对最后一轴进行排序
np.sort(d)

array([[ 0,  1,  5,  7, 10],
       [ 0,  1,  4,  8, 10],
       [ 0,  2,  3,  4, 11]])

In [11]:
#可以手动设置轴axis参数的值
np.sort(d,axis=0)

array([[ 3,  0,  0,  0,  7],
       [ 5,  1,  2,  1, 10],
       [ 8, 10,  4,  4, 11]])

* 会改变数组本身的形式,ndarray.sort()

In [13]:
d2=np.random.randint(0,15,size=(3,5))
d2

array([[14, 11, 13,  7,  3],
       [ 6, 11, 11, 13, 13],
       [ 6, 10,  1, 14,  9]])

In [14]:
d2.sort()

In [17]:
d2

array([[ 3,  7, 11, 13, 14],
       [ 6, 11, 11, 13, 13],
       [ 1,  6,  9, 10, 14]])

2. np.argsort(),返回排序后的下标值

In [19]:
np.argsort(d)

array([[2, 3, 0, 4, 1],
       [3, 1, 2, 0, 4],
       [1, 2, 0, 3, 4]])

In [20]:
np.argsort(d,axis=0)

array([[2, 2, 0, 1, 0],
       [0, 1, 2, 0, 1],
       [1, 0, 1, 2, 2]])

3. 排序方向的设置

先让数组的负数排序，之后再将排序的数组前加负号

In [22]:
-np.sort(-d)

array([[10,  7,  5,  1,  0],
       [10,  8,  4,  1,  0],
       [11,  4,  3,  2,  0]])

In [25]:
# 第二种获取逆向(从大到小)的数据方法是见获取数组负数的下标，再使用np.take()函数获得
indexs=np.argsort(-d)
np.take(d,indexs)

array([[10,  7,  5,  1,  0],
       [ 7,  5,  0, 10,  1],
       [ 7,  1,  5,  0, 10]])