## numpy的其他补充函数

In [2]:
import numpy as np

1. np.apply_along_axis:沿着某个轴执行某个函数

例如自定义函数(def),可以通过这个函数作用给数组中的某个值。类似与map函数。

apply_along_axis(func1d, axis, arr, *args, **kwargs)

* func1d:函数名称，自建函数或者是内置函数 
* axis:函数作用的轴。传入轴当作参数传给函数。
* arr:传入的数组
* return:函数的返回值，是将输入函数每次返回值放在数组中统一进行返回

In [19]:
#  自定义函数：这对数组求除掉最大值、最小值之外数据的平均值
def a_mean(a_array):
    b_array=a_array[(a_array!=a_array.max())&(a_array!=a_array.min())]
    the_mean = b_array.mean()
    return the_mean

In [13]:
d = np.random.randint(0,18,size=(3,5))
d

array([[15, 13, 14,  7,  1],
       [11,  6, 15,  2,  0],
       [ 1, 14,  0, 10, 10]])

In [15]:
np.apply_along_axis(a_mean,axis=1,arr=d)

array([11.33333333,  6.33333333,  7.        ])

2. np.linspace(),将输入两个数区间平均分为几份

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

Parameters
    ----------
    start : 开始数，The starting value of the sequence.
    stop : 终止数
        The end value of the sequence, unless `endpoint` is set to False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bool, optional
        If True, return (`samples`, `step`), where `step` is the spacing
        between samples.
    dtype : dtype, optional
        The type of the output array.  If `dtype` is not given, the data type
        is inferred from `start` and `stop`. The inferred dtype will never be
        an integer; `float` is chosen even if the arguments would produce an
        array of integers.
    
    Returns
    -------
    samples : ndarray,返回值一般为ndarray数组

In [23]:
np.linspace(0,9,3)

array([0. , 4.5, 9. ])

3. np.unique返回数组中的唯一值

unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)

参数说明:
ar:传入的数组
return_counts:出现数据对应出现的次数。此时返回两个数组，即唯一数数组和出现次数数组。

In [25]:
d2 = np.random.randint(0,9,size=(4,4))
d2

array([[8, 4, 3, 1],
       [4, 2, 6, 8],
       [3, 7, 0, 6],
       [3, 0, 0, 0]])

In [27]:
#返回所有数组中出现的唯一值
np.unique(d2)

array([0, 1, 2, 3, 4, 6, 7, 8])

In [29]:
#在np.unique函数中传入return_counts=True参数之后，返回元组中包含两个数组。
#一个数组是唯一值数组，另一个是唯一值对应的出现次数。
np.unique(d2,return_counts=True)

(array([0, 1, 2, 3, 4, 6, 7, 8]), array([4, 1, 1, 3, 2, 2, 1, 2]))

In [30]:
help(np.unique)

Help on function unique in module numpy:

unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)
    Find the unique elements of an array.
    
    Returns the sorted unique elements of an array. There are three optional
    outputs in addition to the unique elements:
    
    * the indices of the input array that give the unique values
    * the indices of the unique array that reconstruct the input array
    * the number of times each unique value comes up in the input array
    
    Parameters
    ----------
    ar : array_like
        Input array. Unless `axis` is specified, this will be flattened if it
        is not already 1-D.
    return_index : bool, optional
        If True, also return the indices of `ar` (along the specified axis,
        if provided, or in the flattened array) that result in the unique array.
    return_inverse : bool, optional
        If True, also return the indices of the unique array (for the specified
        axis, if pro